OPHJOD-298: Add Tag component
Opetushallitus/jod-design-system pull request #47
Opened 2024-04-30 08:54 UTC by ketsappi

## Description

- Add Tag component
- Add bold variant for size-24 icon

## Related JIRA ticket

https://jira.eduuni.fi/browse/OPHJOD-298

2024-05-07 09:35 UTC, ketsappi commented on lib/components/TagsInput/TagsInput.tsx
> +                      <div className="inline-flex items-center">
This `div` is added so that the `hidden` attribute that Ark adds, will work (giving any `display` value will override `hidden` attribute).

2024-05-07 10:50 UTC, sauanto requested changes

2024-05-07 10:50 UTC, sauanto commented on lib/components/TagsInput/TagsInput.tsx
> +              <ArkTagsInput.Control className="flex gap-x-3">
```suggestion
              <ArkTagsInput.Control className="flex flex-wrap gap-3">
```

2024-05-07 10:50 UTC, sauanto commented on lib/components/TagsInput/TagsInput.tsx
> +                        <ArkTagsInput.ItemDeleteTrigger>
```suggestion
                        <ArkTagsInput.ItemDeleteTrigger className="flex">
```

2024-05-07 10:50 UTC, sauanto commented on lib/components/TagsInput/TagsInput.tsx
> +                        <ArkTagsInput.ItemText className="hyphens-auto py-[5px] text-secondary-gray group-hover:underline">
```suggestion
                        <ArkTagsInput.ItemText className="hyphens-auto text-secondary-gray group-hover:underline">
```

2024-05-07 10:50 UTC, sauanto commented on lib/components/TagsInput/TagsInput.tsx
> +                    <ArkTagsInput.ItemInput />
```suggestion
                    <ArkTagsInput.ItemInput className="py-[5px]" />
```

2024-05-08 06:35 UTC, sauanto approved these changes

2024-05-08 07:30 UTC, sauanto approved these changes

2024-05-08 09:53 UTC, merged